# Generated by Django 4.1.7 on 2023-03-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dialogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=10)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("kind", models.CharField(max_length=50)),
                (
                    "dialogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.dialogue"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
