# Generated by Django 4.1.7 on 2023-03-11 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="body",
            new_name="content",
        ),
    ]
